---
- name: Create sshd_config
  template:
    src: opensshd.conf.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart sshd
  when: ssh_server_hardening

- name: Create ssh_config
  template:
    src: openssh.conf.j2
    dest: /etc/ssh/ssh_config
    mode: 0644
    owner: root
    group: root
  when: ssh_client_hardening
